Description: This template creates a bucket that is publicly accessible
  and automatically configured for static web hosting
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Bucket Name
        Parameters:
          - MyBucketName
    ParameterLabels:
      MyBucketName:
        default: "NOTE: Must be globally unique -- generic names are probably already claimed. Bucket names must be between 3 and 63 characters long. Bucket names can consist only of lowercase letters, numbers, dots (.), and hyphens (-). Bucket names must begin and end with a letter or number."
Parameters:
  MyBucketName:
    Type: String
    AllowedPattern: "[a-z0-9]+[a-z0-9.-]+[a-z0-9]+"
    MinLength: 3
    MaxLength: 63
    ConstraintDescription: Bucket names must be between 3 and 63 characters long. Bucket names can consist only of lowercase letters, numbers, dots (.), and hyphens (-). Bucket names must begin and end with a letter or number.
Resources:
  VeryPublicBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref MyBucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html
  UploadToPublicBucketRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - 
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
  VeryPublicBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Join
              - ""
              - - "arn:aws:s3:::"
                - !Ref VeryPublicBucket
                - /*
          - Sid: WriteForLambdaRole
            Effect: Allow
            Principal:
              AWS: !GetAtt UploadToPublicBucketRole.Arn
            Action: "s3:PutObject"
            Resource:
              - !Join
                - ""
                - - "arn:aws:s3:::"
                  - !Ref VeryPublicBucket
              - !Join
                - ""
                - - "arn:aws:s3:::"
                  - !Ref VeryPublicBucket
                  - /*
      Bucket: !Ref VeryPublicBucket

Outputs:
  WebsiteURL:
    Value: !GetAtt
      - VeryPublicBucket
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join
      - ""
      - - "https://"
        - !GetAtt
          - VeryPublicBucket
          - DomainName
    Description: Name of S3 bucket to hold website content
