Description: This template creates a bucket that is publicly accessible
  and automatically configured for static web hosting
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Bucket Configuration
        Parameters:
          - MyBucketName
    ParameterLabels:
      MyBucketName:
        default: The name of your S3 bucket, please make sure that it is a legal S3 name and bear in mind that all S3 names must be globally unique -- generic names are likely to already be taken.
Parameters:
  MyBucketName:
    Type: String
Resources:
  VeryPublicBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref MyBucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html
  VeryPublicBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Join
              - ""
              - - "arn:aws:s3:::"
                - !Ref VeryPublicBucket
                - /*
      Bucket: !Ref VeryPublicBucket
Outputs:
  WebsiteURL:
    Value: !GetAtt
      - VeryPublicBucket
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join
      - ""
      - - "https://"
        - !GetAtt
          - VeryPublicBucket
          - DomainName
    Description: Name of S3 bucket to hold website content
